# Generated by Django 6.0.2 on 2026-05-08 09:26

import commongrounds.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0002_project_creator_favorite_projectrating_projectreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreview',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=commongrounds.storage.CloudinaryStorage(), upload_to='images/'),
        ),
    ]
