# Generated by Django 6.0.2 on 2026-03-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('A', 'Anonymous'), ('MS', 'Market Seller'), ('EO', 'Event Organizer'), ('BC', 'Book Contributor'), ('PC', 'Project Creator'), ('CM', 'Commission Maker')], default='A', max_length=20),
        ),
    ]
