# Generated by Django 6.0.2 on 2026-05-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0002_product_owner_product_product_image_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('On sale', 'On sale'), ('Out of stock', 'Out of stock')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('On cart', 'On cart'), ('To pay', 'To pay'), ('To ship', 'To ship'), ('To receive', 'To receive'), ('Delivered', 'Delivered')], max_length=20),
        ),
    ]
