# Generated by Django 6.0.2 on 2026-05-08 09:26

import commongrounds.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0003_alter_product_status_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(storage=commongrounds.storage.CloudinaryStorage(), upload_to='images/'),
        ),
    ]
