# Generated by Django 6.0.2 on 2026-03-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-publication_year'], 'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
        migrations.AlterModelOptions(
            name='bookcategory',
            options={'ordering': ['name'], 'verbose_name': 'book category', 'verbose_name_plural': 'book categories'},
        ),
    ]
