# Generated by Django 6.0.2 on 2026-05-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0003_book_available_to_borrow_book_contributor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='date_to_return',
            field=models.DateField(blank=True, null=True),
        ),
    ]
