# Generated by Django 6.0.2 on 2026-05-02 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookclub', '0004_alter_borrow_date_to_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='anon_reviewer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='user_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
