# Generated by Django 6.0.2 on 2026-02-22 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'commission type',
                'verbose_name_plural': 'commission types',
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('people_required', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('commission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='commissions.commissiontype')),
            ],
            options={
                'ordering': ['created_on'],
                'verbose_name': 'commission',
                'verbose_name_plural': 'commissions',
            },
        ),
    ]
