
# Generated by Django 6.0.2 on 2026-05-08 10:23

import commongrounds.storage
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('localevents', '0002_event_event_capacity_event_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',

            field=models.ImageField(
    blank=True,
    max_length=500,
    null=True,
    storage=commongrounds.storage.CloudinaryStorage(),
    upload_to='images/'
            ),
        ),
    ]
